cabal-version:       3.8
name:                hslib
version:             0.1.0.0
build-type:          Simple

foreign-library asplib
   type:                native-shared
   options:             standalone
   hs-source-dirs:      .

   if os(Windows)
--   required for fuckass windows. I spent 4 fucking hours on this shit
     mod-def-file: asplib-def.def

   other-modules:
      ASPLib
      Data.Retrieval

   build-depends:
      base,
      req,
      aeson,
      text,
      bytestring

   default-language:		Haskell2010

   -- ghc-options: -shared -fPIC
   -- ld-options: -shared

