#include <HsFFI.h>
#include "cpp/window.h"

#include "Main_stub.h" // Generated by GHC

int main(int argc, char* argv[]) {
	hs_init(&argc, &argv);

	Window window = Window();
	printf("Haskell: %d\n", haskell_add(1, 2));

	hs_exit();
    return 0;
}
